version: '3.9'

services:
    db:
        container_name: jc-db
        image: postgres
        environment:
            - POSTGRES_PASSWORD=postgres
            - PGDATA=/pgdata
        ports:
            - 5432:5432
        volumes:
            - jcdatabase:/pgdata
volumes:
    jcdatabase:
        name: jcdatabase
